name: quran_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.4
  path_provider: ^2.0.11
  scroll_to_index: ^3.0.1
  sqflite: ^2.0.3
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Thin.otf
          weight: 200
